### ISSUE TITLE
BoofCV Kotlin

### ISSUE THREAD

**Issue by waicool20** [lessthanoptimal/BoofCV#148]
Seeing as you had some interest in kotlin integration, was just wondering where would I put kotlin code in the current project structure, as I see it there are two ways we could go about this. 

Some libraries might just do the obvious way which have `src/main/java` and `src/main/kotlin` in the same module. 

But there are also some projects which offer a separate library to offer kotlin support like how the jackson json library has `jackson-module-kotlin`. For your project it could be `boofCV-extensions`, `boofKV`  etc

I already have some kotlin code right here that I use personally, and I don't mind expanding the scope a bit (like the rest of the PixelMath ops) to cover the rest of the stuff i omitted and then PR it into BoofCV:
https://github.com/waicool20/CVAuto/blob/master/modules/core/src/main/kotlin/com/waicool20/cvauto/util/ImageExtensions.kt

I personally would like to see at least a kotlin shimming layer especially on the libraries generics situation, seeing that an increasing number of apps on Android are using kotlin for dev and this is a good library if you want to a full jvm implementation. I also open this issue for open discussion for other integration issues and methods.

**Comment by lessthanoptimal** [comment]
To make things easy I just modified SNAPSHOT so that it has a new module: boofcv/integration/boofcv-kotlin/ I copied a couple of your functions for the initial seed. For a while at least, the main code will be entirely Java. Although if Java had extensions like Kotlin I would have definitely designed the library differently. The reason for all the Util and Ops classes was primarily for code maintainability. Putting everything into one class results to a 20k long file.

Anyways, I like what I see there. You can pretty much experiment in your own fork for a bit. The final version I suspect will involve automatically generate code to support all the BoofCV image types. Auto code generation is an area I was considering switching to Kotlin too.

**Comment by waicool20** [comment]
Was writing all the extensions by hand so far but it does seem a bit much apparently, go figure. So now I'm trying to see how to use kotlin poet for code generation.

**Comment by lessthanoptimal** [comment]
If you search for `CodeGeneratorBase` in BoofCV you will find a bunch of examples for how it is done now. GenerateImplPixelMath might be a good starting point. The class `AutoTypeImage` provides type specific information. Kinda like numerics<int> in C++

**Comment by lessthanoptimal** [comment]
I'm been using Kotlin on some other projects and adding extensions as it seems to make sense. For now just add whatever you think is useful. I'm not bothering with KDoc at the moment until things stabilize.  Is there any other features you think besides extensions that could be useful?

**Comment by lessthanoptimal** [comment]
Kotlin Extensions have been in BoofCV for a bit now in an integration module.
