### ISSUE TITLE
Kannala-Brandt distortion model supported?

### ISSUE THREAD

**Issue by ecmnet** [lessthanoptimal/BoofCV#151]
A short question. Does boofcv support the Kanalla-Brandt distortion model to rectify wide angle images?

**Comment by lessthanoptimal** [comment]
Not yet. This has come up before. I'll look into it. By support do you mean being able to calibrate a camera with that model and/or use the model in BoofCV?

**Comment by lessthanoptimal** [comment]
http://www.ee.oulu.fi/~jkannala/publications/tpami2006.pdf

**Comment by ecmnet** [comment]
> Not yet. This has come up before. I'll look into it. By support do you mean being able to calibrate a camera with that model and/or use the model in BoofCV?

Exactly.

**Comment by lessthanoptimal** [comment]
I've started adding support but it's a background project. That means it's probably months away, but maybe I'll be bored one weekend. 

https://github.com/lessthanoptimal/BoofCV/tree/feature/fisheye2

**Comment by lessthanoptimal** [comment]
Any reason for this camera model? I know it's popular but have you tried the universal omni one that's already included? Curious if its better in some way.

**Comment by olegvakulenko** [comment]
For me personally, if I correctly understood the description of the method, it is interesting whether this method will make the process of calibrating cameras with a fisheye lens easier. I mean how many images will be needed to calculate the distortion parameters. Correct me if I am wrong.

**Comment by lessthanoptimal** [comment]
Would need to double check, but I believe this method has more parameters than the current approach. It's probably the same level of difficulty is my guess. I've not used it so I'm not sure if it's a better model or not. The author published working matlab code so that will make implementing it much easier.

**Comment by ecmnet** [comment]
Using the dev. branch for this feature seems to work for me already. Many thanks.

**Comment by lessthanoptimal** [comment]
Wait it works? Never finished it, still on the TODO list. Did you get the parameters from another application and you're using that?

**Comment by lessthanoptimal** [comment]
A bit later than expected, but it's fully integrated now:

https://github.com/lessthanoptimal/BoofCV/pull/290

Should be merged into SNAPSHOT soon. A new PR is being made to improve the application app to handle multiple fisheye models. It was hard coded to Universal in a few locations since it was the only model until now.

**Comment by lessthanoptimal** [comment]
done
