### ISSUE TITLE
Median BlurFilter for different X/Y

### ISSUE THREAD

**Issue by thhart** [lessthanoptimal/BoofCV#173]
The median blur filter is superior to the mean filter, it would be great to have a filter with x/y instead of radius only. This is the case for mean already.

**Comment by lessthanoptimal** [comment]
I'll take a look into adding this. need to get a few other things working first though.

**Comment by lessthanoptimal** [comment]
started working on this feature

**Comment by thhart** [comment]
Cool, will check soon. Do you have nightly builds somewhere or should I checkout?

**Comment by lessthanoptimal** [comment]
Will need to check it out. No nightly builds yet.

**Comment by thhart** [comment]
Hi Peter, working great, no complaints. I could offer implement some Junit and commit if needed, just let me know...
I think the new functionality must be ported to FactoryBlurFilter still, if you are out of time I can do maybe also...

**Comment by lessthanoptimal** [comment]
Yep looks like it has not made it into FactoryBlurFilter yet. If you could add that, that would help. Thanks!

Looks like It is already unit tested in `TestBlurImageOps`. That code is also fairly complex due to reflections. Interestingly, there are no unit tests for `GBlurImageOps` yet. That would also require iterating through all supported image types and comparing the results to `BlurImageOps`.
