### ISSUE TITLE
"Call the other start camera function" Runtime Exception when trying to get camera permissions

### ISSUE THREAD

**Issue by Psijic** [lessthanoptimal/BoofCV#182]
Hello, I don't know how and why this parent class function is called while there is an inner function should be called. But it happens when I'm trying to ask camera permissions before starting the camera:

`SimpleCamera2Activity` calls its parent's

`VisualizeCamera2Activity`

```
@Override
protected void startCamera() {
    throw new RuntimeException("Call the other start camera function");
}
``` 
in `protected void onResume()`
and I can't override this method with Kotlin because it's protected, not public.

My code is: 
```
override fun onCreate(savedInstanceState: Bundle?) {
        ...
        if (isPermissionGranted(Manifest.permission.CAMERA)) startCamera(cameraView, null)
        else requestPermission(Manifest.permission.CAMERA, CAMERA_PERMISSION_CODE)
}
```

**Comment by lessthanoptimal** [comment]
What it wants you to do is to call `protected void startCamera( @NonNull ViewGroup layout, @Nullable TextureView view )`. I can't remember the reason for this design since it's been a while.

Here's a code example:
https://github.com/lessthanoptimal/BoofCV/blob/v0.36.1/integration/boofcv-android/examples/video/app/src/main/java/org/boofcv/video/GradientActivity.java

**Comment by Psijic** [comment]
Because of this problem I moved my asking camera permission dialog to the previous activity. But it should be better to ask it from the `Camera2Activity` itself after all GUI is loaded.
