### ISSUE TITLE
Camera doesn't support Android API < 22

### ISSUE THREAD

**Issue by Psijic** [lessthanoptimal/BoofCV#188]
Hello. Currently there are still many devices use Android API 19-21 but there is no support for them. After I try to scan QR code with BoofCV, I have a crash.
The devices involved are not only phones but also Amazon Kindle Fire uses Android 4.4 widely.

**Comment by lessthanoptimal** [comment]
Sorry for the delay in getting back to all your questions. Got distracted by some progress in generating 3D images.

Anyways, there are two issues which determine the minimum allowed version of BoofCV on Android. Short version, if you ditch BoofCV's camera integration code you can run it on much older versions of Android.

1) The core BoofCV library requires Java 1.8 compatibility, in particular support for Lambdas. The good news here is that this is primarily dependent on the Android Gradle Plugin you use, see https://developer.android.com/studio/write/java8-support. The first release of BoofCV on Android ran on some very old Android devices.

 2) Minimum API version of features used in BoofCV's Android Integration. The most obvious hard limit is on use of Camera 2 API, which was introduced in Android 21. I think the old Camera 1 API code is still around, but hasn't been updated in sometime. There also might be random Android API bugs that got fixed in later versions. I have a vague memory of a Android Camera 2 bug forcing API 22 to the minimum since that API was broken when first released.

I've been contemplating switching to a 3rd party camera library since I simply don't do enough Android development right now to keep it up to date with the constantly changing standards. Extending an Activity directly hasn't been the recommended approach for years and basically is difficult for people to work with.

If you want to give another 3rd party library a try which simplifies working with Camera 2 API I'll help out with that since I should be looking for alternatives.
