### ISSUE TITLE
BoofConcurrency creates a ForkJoinPool without any option to properly shut it down

### ISSUE THREAD

**Issue by LStampf** [lessthanoptimal/BoofCV#205]
BoofConcurrency(or its base class) contains a static field pool with a ForkJoinPool. This gets loaded as soon as the class is loaded. But there is no shutdown method or getter, making it impossible to stop the pool. This means you can't properly shutdown every application using BoofCV because the Threads are still alive.

**Comment by lessthanoptimal** [comment]
Is this only an issue if the process is still running? Or are you saying that it just hangs even after the operation is finished? Something else?

**Comment by LStampf** [comment]
The problem is you can't stop the pool (e.g. when you need to shutdown the application) properly. As BoofConcurrency.pool no longer works (why was this removed?) you can't properly stop the application anymore without accessing the pool via Reflection and calling shutdownNow() on it.

**Comment by lessthanoptimal** [comment]
It's been added back here https://github.com/lessthanoptimal/ejml/pull/128 . If you use the SNAPSHOT you should have access to it again later today without reflection. It's in a different project since there is a chain of 4 projects which all use this code. It will probably be forked into it's own library in the future.

I can't remember why it was made private. Probably just to hide the internal implementation. I've not had any issues with applications hanging due to the thread pool not being shutdown, however you might be wanting to exit before the concurrent process has finished and that would hang.

**Comment by lessthanoptimal** [comment]
closing this since it's been in SNAPSHOT for a few days now. Feel free to re-open if there's still an issue.
