### ISSUE TITLE
It's not clear which coordinate system UtilPolygons2D_I32.isCCW uses

### ISSUE THREAD

**Issue by DCNick3** [lessthanoptimal/BoofCV#210]
Depending on choice of axes directions, notion of being CCW is reversed: what is CCW in Y up, X right coordinate system is actually CW in Y down, X right coordinate system.

It seems that this function checks polygon being CCW in former case, while used in context where latter seems more fit (`DetectPolygonFromContour`; historically in computer images Y is directed down).

I think the name/description should be clarified, this misunderstanding submerged me into debugging for quite some time =)

**Comment by lessthanoptimal** [comment]
Completely understandable confusion here. Typically functions that are in GeoRegression (since it's not computer vision specific) define 2D as +y up and +x right. I do remember running into a bit of chaos in the code when at first it tried flip everything into the CV standard and decided it was less confusing to go with the geometry standard.

I'll look into fixing this by  making sure all the javadoc points out what is going on here.

**Comment by lessthanoptimal** [comment]
Clarified the meaning by updating the variable name and Javadoc. This probably needs to be done in several other parts of the code, but it's a start at least. PR https://github.com/lessthanoptimal/BoofCV/pull/217
