### ISSUE TITLE
Bug: Fails scanning QR codes generated by Python qrcode lib

### ISSUE THREAD

**Issue by wkornewald** [lessthanoptimal/BoofCV#312]
For the German Covid vaccination record/passport we switched from ZXing to BoofCV because that worked more reliably during our tests. However we've now received a bug report where people can't scan QR codes generated with the Python qrcode library:

https://github.com/Digitaler-Impfnachweis/covpass-android/issues/93

That ticket contains a failing QR code, so you could debug the issue. Could you please have a look?

**Comment by lessthanoptimal** [comment]
Thanks for the bug report. Did a very quick check and verified it's not reading the first QR code and tried a few other libraries on my Android device which could read it. Haven't seen any obvious reason for it failing. All the debug app says is that it's failing at error correction stage but everything else looks good. Hard to tell if it's a bug in BoofCV or a bad QR code. BoofCV is more strict on QR codes being standard compliant, but since you posted the python code I should be able to figure out what's going on.

**Comment by lessthanoptimal** [comment]
![image](https://user-images.githubusercontent.com/739159/139712123-2430aec4-6889-4043-9873-109154b680a0.png)

I'm fairly confident the encoder is non-compliant and is doing a transpose of the correct bit order. I'll do one last check to make sure and that is flip the bits in BoofCV's decode and see if it works.

In the attached screenshot, If you scan down the right column in this image it will match the bottom row in the image you posted. This is a fairly common failure mode for encoders and a lot of libraries will automatically try scanning with a transposed order. I'm considering adding an optional flag to compensate for this type of error but will need to be careful that it doesn't slow things down.

**Comment by lessthanoptimal** [comment]
Did a simpler test and just transposed the image. BoofCV could then read the marker without any problem. If you wish to keep on using the same encoder you can make it compliant by transposing the image. A bug report should also be created since the encoder is most likely not handling a coordinate transform correctly and not all libraries will be able to decode it. If the author compares their generated QR code to some of the references in the ISO standard they will see it doesn't match.

**Comment by wkornewald** [comment]
Thanks for taking the time to analyze the cause. Indeed, transposing fixes the issue.

Maybe you could provide a multi-threaded scanner which can deal with this apparently common kind of bug in QR encoders? If that's not possible for some reason, at least some simple API to deal with this case and allow the implementer to use multi-threading would  be nice.

In the end, everyone who wants to use the BoofCV QR scanner will run into this issue and from a practical point of view everyone will need to somehow solve this problem. Reliable scanning is more important than being the fastest scanner in the world.

**Comment by lessthanoptimal** [comment]
Created a new ticket for this. I think this capability can be added and not make the code a lot more complex or slow it down when turned off.

https://github.com/lessthanoptimal/BoofCV/issues/313

Too bad an easy compliance check was never released for QR codes in the early days. As a result the ISO standard is treated as more of a suggestion and there are a ton of defacto "standards" or variants.

**Comment by pavinjosdev** [comment]
> people can't scan QR codes generated with the _Python qrcode library_

> Too bad an easy compliance check was never released for QR codes in the early days. As a result the ISO standard is treated as more of a suggestion and there are a ton of defacto "standards" or variants.

Isn't this an issue that should be solved by the non-compliant QR code library?
Props to BoofCV for addressing this, but ideally the root cause should've been fixed over at the Python qrcode library.
