### ISSUE TITLE
ExampleTrifocalStereoUncalibrated giving inaccurate results

### ISSUE THREAD

**Issue by sandeepnmenon** [lessthanoptimal/BoofCV#318]
I am trying the ExampleTrifocalStereoUncalibrated on my data and the intrinsics are way off. I am suspecting a mismatch in the type of images the algorithm expects and my data.

Data: https://drive.google.com/drive/folders/1UjYqxrtLnxWuLq12wXYR5hknom1_Bj9i?usp=sharing

Intrinsics obtained from Checkerboard
```
{
    "fx": 4491.4955129238315,
    "fy": 4038.8114057090834,
    "cx": 1172.6434446843996,
    "cy": 2356.214713124951,
    "k1": 0.035995993874533824,
    "k2": -0.3380135040013434,
    "p1": -0.0004710834517012656,
    "p2": 0.0018332742028537906,
    "k3": 1.0343555938511344,
    "camera_model": "normal",
    "reprojection_error": 1.8074380776914334
}
```
Intrinsics obtained from the Trifocal tensor. The rectified K is
```
Rectified K
Type = DDRM , rows = 3 , cols = 3
 486.985048  0           2382.45056
 0           486.985048  595.412724
 0           0           1  
```

Intrinsics matrix is shown as
`Intrinsic 01: BundlePinholeSimplified{f= 4965.71674, k1= .408273828, k2=-4.56486747}`

projective camera matrices as below
```
Refining projective camera matrices
fx=2438.6717492079183 fy=2438.6717492079183 skew=0.0
fx=2439.046808302179 fy=2439.046808302179 skew=0.0
fx=2490.029124104254 fy=2490.029124104254 skew=0.0
```

From the tutorial video, I understand the images need a lot of texture. From the example data I see pictures of books in the table. So my data with the laptop and its keyboard should provide sufficient texture right?

**Comment by lessthanoptimal** [comment]
![image](https://user-images.githubusercontent.com/739159/145504084-8a49368a-6157-4df9-96f0-87cdfd93e7ca.png)

**Comment by lessthanoptimal** [comment]
produced reasonable results when I processed those images on my computer when I used the demo application. The code isn't exactly the same as the example code so that might be the difference. This type of reconstruction can be a bit unstable and small changes in input an tuning parameters can make a big different. More work is needed there.

**Comment by sandeepnmenon** [comment]
@lessthanoptimal 
thank you for trying out with my data. 
I did try out with the example code after running the exampleJar. Can you share the code that you tried?

So what kind of data would give good results. Also, this algorithm assumes fx=fy correct?

**Comment by lessthanoptimal** [comment]
There are examples and demonstrations in BoofCV. Examples is intended to have easy to read and understand code. Demonstrations is intended to make it easy to run the code in a GUI.

In the image above I used Demonstration application instead of the example code. Primarily for historical reasons, the example code basically rewrites an implementation of [ThreeViewEstimateMetricScene](http://boofcv.org/javadoc/boofcv/alg/structure/ThreeViewEstimateMetricScene.html) from scratch. The demo code uses ThreeViewEstimateMetricScene. ThreeViewEstimateMetricScene has some more recently improvements and isn't identical to the example code any more. We should probably update the example code to use ThreeViewEstimateMetricScene, even if it's more of a black box and not as interesting to a researcher.

**Comment by lessthanoptimal** [comment]
As for good images, you want a scene with plenty of texture, diffuse lighting, objects that are up close and far away, not planar, and a baseline that's not too small or big. The image below produces fairly stable results.

![image](https://user-images.githubusercontent.com/739159/146699326-1980bb2d-3bb3-4873-905a-891b03567dfe.png)

**Comment by lessthanoptimal** [comment]
Yes for fx=fy. You will be hard pressed to find a lens for which that's a bad assumption. Almost any cellphone camera will work. Just make sure there isn't motion blur. Some cheaper phones are prone to issues in low lighitng.

**Comment by sandeepnmenon** [comment]
Thank you for the insights. Closing the issue,
