### ISSUE TITLE
ConfigSquare cols and rows should be specified correct

### ISSUE THREAD

**Issue by thhart** [lessthanoptimal/BoofCV#37]
For calibration with square patterns you are using a approach of specifying rows and columns including white space (left over from chess pattern I believe). This make the algorithm only work with patterns of uneven squares and also hard to use. Instead I suggest to use the real square amount in ConfigSquare  and all its dependencies like for example PlanarDetectorSquareGrid:
<pre>
-		detect = new DetectSquareGridFiducial<ImageFloat32>(config.numRows/2+1,config.numCols/2+1,
+		detect = new DetectSquareGridFiducial<ImageFloat32>(config.numRows,config.numCols,
</pre>

**Comment by lessthanoptimal** [comment]
Since I've been messing around with fiducials recently this is something I have been thinking about.  It especially makes sense when you don't have square spaces between black squares.  You're right it's leftover from chessboard and a very early version did specify the grid the way you're suggesting.

The next version is basically ready to be released.  I'll make a note to seriously consider this modification in 0.21.  Bit of a pain since there is lots of code and documentation that needs to be adjusted.

**Comment by thhart** [comment]
Better sooner than later. ;-)
Created a pull request for it, sorry for optimizing imports, Idea to blame.

**Comment by lessthanoptimal** [comment]
haha ok.  I'll accept the pull request, but after I finish with this release.  If you sent the patch a few days earlier it would have made it in.  The next release has an actual plan with a smaller set of new features, all calibration related.  This change will fit in nicely with that.

**Comment by lessthanoptimal** [comment]
The current SNAPSHOT has this change in it.  Validation Boof has also been updated
