### ISSUE TITLE
missing BufferedImage and Graphics2D

### ISSUE THREAD

**Issue by huahua713** [lessthanoptimal/BoofCV#67]
Hi, I'm trying to test the example here https://boofcv.org/index.php?title=Example_Image_Stitching to see how it works on Android. 

I included `compile 'org.boofcv:all:0.26'` in my gradle file and copy everything from the `ExampleImageStitching` and I'm getting errors saying cannot resolve symbol BufferedImage and Graphics2D. I tried googling to find the jar file but didn't have any luck. Can someone please help me out with it? Thank you so much

**Comment by lessthanoptimal** [comment]
Did you include the import?  Example code online doesn't have boiler plate that's typically added by the IDE.  Example code included with the source code has it.

**Comment by huahua713** [comment]
yes, otherwise i would have more errors. I asked on stackoverflow and people said that package is not available in Android. meaning image stitching isn't available in android?

**Comment by lessthanoptimal** [comment]
Sorry I missed a keyword in your problem description when I read it.  That word is Android.   BufferedImages are a swing concept and not included with Android because they have their own way.  You will need to modify the code to work on Android.

You will need to load the images you wish to stitch in Android as a Bitmap image.  BoofCV provides an Android package that can convert Bitmap images into BoofCV image types.  After the image has been converted everything is the same until you want to visualize it.  At that point you need to convert the stitched image back into a Bitmap image then draw anything else that you want on it using Android specific functions.

Since this isn't really a bug could you move follow up questions to the BoofCV message board?

https://groups.google.com/group/boofcv?pli=1

**Comment by huahua713** [comment]
Thank you @lessthanoptimal
