### ISSUE TITLE
[Feature Request] Turn Runtime Benchmarks into Regression Tests

### ISSUE THREAD

**Issue by lessthanoptimal** [lessthanoptimal/BoofCV#87]
There are a bunch of random benchmarks used through out of BoofCV. Turn these into a regression test that can be run automatically. The results can then be examined to see if performance has changed in some way for the worse/better and investigated.

Example: BenchmarkAverageDownSample

Just search for classes named Benchmark* to find the rest.

**Comment by lessthanoptimal** [comment]
Started switching benchmarks over to JMB

**Comment by lessthanoptimal** [comment]
@jdeca569 Moving the discussion over here. I agree with you 100% that BoofCV should use JMH for it's benchmarking. New internal benchmarks in BoofCV are already using JMH and the project is dependent on JMH. Help transitioning over all the other internal benchmark to JMH would be appreciated.

The problem was that you posted inside the Java Matrix Benchmark project and discussed a BoofCV issue there. There is literally zero common code between those two projects and they have very different micro benchmark needs. BoofCV is not dependent on Java Matrix Benchmark. Maybe the confusion arose from my March 13 comment having a type-o. JMB instead of JMH.

**Comment by jdeca569** [comment]
I see indeed, i've completely mixed the two projects.

I would be pleased to help once the of the BoofCV project design and workflow fits into my head. 
It will probably not be clear to me that soon because i've never taken the step of using gradle instead of maven, and to be honest it kind of scares me...

The good thing with all the existing benchmarks is the Performer abstraction i believe. My first idea was to have a similar interface but forcing the process() method to return the computed value. A big part of the existing benchmark code could perhaps be kept almost as-is.
That is too soon for me to assume though.

I can see 3 JMH benchmarks but couldn't figure out yet how it is (or should be) part of the build. I will follow closely the project activity and maybe it will be clear at some point.

**Comment by lessthanoptimal** [comment]
This is actually happening! Starting in the current SNAPSHOT, all internal benchmarks have been updated to use JMH. I've already written code and have running in "production" a JMH regression for another project. I need to generalize the code then bring it into BoofCV and other projects.

As a side comment, getting reproducible runtime benchmarks is not trivial at all. On a dedicated machine there seems to be a false positive rate of about 1%.  That 1% FP rate includes running a test up to 10 times if it fails. I suspect that I need to modify BIOS settings to limit maximum CPU speed and throw the computer into performance mode for the benchmarks.
